### ISSUE TITLE
Error in callback for watcher "features"

### ISSUE THREAD

**Issue by Gaetanbrl** [ghettovoice/vuelayers#170] opened 2019-05-24 08:51 UTC
Hi !
In an autocomplete component, i get an adress with the location to display a point in the map.

I get this feature when i select an adress : 

![image](https://user-images.githubusercontent.com/16317988/58314577-1c3f5580-7e10-11e9-8bb6-eb05b2fdcf4c.png)

I stock this feature in a store to be share with other component :
```
       // autocomplete.vue file
        this.$store.commit("setSearchFeatures", {
          features: {
            id: selected.properties.id,
            type: "Feature",
            geometry: geom,
            properties: selected.properties
          },
        });
```
This is my store : 

```
// store.vue file
export const store = new Vuex.Store({
    state: {
        // vue layer feature
        searchFeatures: [],
    },
    mutations: {
        setSearchFeatures: function(state,searchFeatures) {
            state.searchFeatures = searchFeatures
        },
    },
    getters: {
        getSearchFeatures: state => state.searchFeatures,
    }
})

```

This is the layer in vuemap.vue file: 
```
      <vl-layer-vector id="featuresLayer">
        <vl-source-vector ident="featuresSource" :features.sync="getSearchFeatures"></vl-source-vector>
        <vl-style-box>
          <vl-style-icon
            src="./img/geoPin.png"
            :scale="scale"
          ></vl-style-icon>
        </vl-style-box>
      </vl-layer-vector>
      <vl-interaction-modify source="featuresSource" ></vl-interaction-modify>
```

where _getSearchFeature_ is in vuemap.vue file : 
  ```
computed: {
    getSearchFeatures: function () {      
      let getFeaturesInfos = this.$store.getters.getSearchFeatures ? this.$store.getters.getSearchFeatures : undefined
      if(getFeaturesInfos){
        return [getFeaturesInfos.features]
      } else {
        return []
      }
    },
  },
``` 

When i start my application and search an adress, i get on point but i don't see the feature and i get this error in the console : 
![image](https://user-images.githubusercontent.com/16317988/58315168-46454780-7e11-11e9-827b-f256081d5927.png)

i don't understand because i have a feature with ID and other properties.
If i search an adress again without reload my application or page, it work and i see my feature.

Do you know this error ?
Thank you !

**Comment by Gaetanbrl** [comment] 2019-05-24 10:52
I had pass this error by create basic OpenLayers 5 vector, feature and add feature by basic function without VueLayers.

**Comment by ghettovoice** [comment] 2019-05-24 12:49
Hello @Gaetanbrl ,
can you make screenshot of the `vl-source-vector` component properties from vue devtools panel? Exactly after you got this error.

Thanks!

**Comment by avpavp** [comment] 2019-06-10 16:06
Hi @ghettovoice,

I'm doing something similar as @Gaetanbrl  - loading the features from a function.  I'm also seeing the same error.  Here's a screenshot as you have requested.

![image](https://user-images.githubusercontent.com/5289624/59208880-97309c00-8b84-11e9-9685-7b60ec9611c7.png)

Please let me know if you need any further info.

Thanks.

**Comment by ghettovoice** [comment] 2019-06-11 06:21
Hello @avpavp ,
thank you for contributing! 

You screenshot looks good, I don't see any problems with component state. I'll try to reproduce this issue with the test app a bit later.

**Comment by avpavp** [comment] 2019-07-12 00:49
Hey @ghettovoice,

I've looked into this further.  The error appears to be occurring due to the incoming features not having an 'id' defined.

When I manually create a uuid and add it to my feature before I have it sync with VL, the error goes away.

In your file features-container.js I added some exception handling in the removeFeature().  It throws on this line:

feature = this.getFeatureById(feature.id);

So I'm not sure if OpenLayers is supposed to add an 'id' to a feature if it doesn't have one?  Or should any user defined external source features be mandatory to have an 'id'?

**Comment by ghettovoice** [comment] 2019-07-12 07:05
> So I'm not sure if OpenLayers is supposed to add an 'id' to a feature if it doesn't have one? Or should any user defined external source features be mandatory to have an 'id'?

OpenLayers doesn't automatically append id to features without it. This is implemented in the VueLayers, because feature id is important to correctly append/remove GeoJSON features .

> I was hoping this failure to remove feature would be the cause of my memory leak, but unfortunately it doesn't appear to be... Any tricks/suggestions for tracking down a memory leak in vue???

I can only suggest comment out layers and uncomment them one by one, and monitor the memory usage in the Chrome

**Comment by ghettovoice** [comment] 2019-07-12 10:39
Patch will be in the next 0.11.5 version

**Closed by ghettovoice** 2019-07-12 10:39 UTC
Labels: bug, clarification, pinned

**Comment by avpavp** [comment] 2019-07-16 01:15
And just to confirm, after this fix, my memory leaks did go away!
