### ISSUE TITLE
How to set id to each feature while using vl-source-vector ?

### ISSUE THREAD

**Issue by chenpion** [ghettovoice/vuelayers#156] opened 2019-04-21 15:31 UTC
Recently I've been using vuelayers on my project.
The situation I'm facing is I had a polygon drawn on the map, vertices styled with a img, and some calculated middle points between each vertex.
Something like the image below
<img width="200" alt="螢幕快照 2019-04-21 23 20 47" src="https://user-images.githubusercontent.com/33650282/56472027-23c7b380-648c-11e9-8008-649c7e197a0e.png">

And I use `vl-interaction-select` to detect selection.
But when I console my selected vertex, I got undefined on it's `id`.
<img width="229" alt="螢幕快照 2019-04-21 23 26 27" src="https://user-images.githubusercontent.com/33650282/56472117-34c4f480-648d-11e9-8fd4-a80716601f91.png">

Is there any way to set ids of each vertex, like `polygon-point-[index]` ?

**Comment by ghettovoice** [comment] 2019-04-22 06:21
Hi @chenpion ,
looks like a bug, each feature should be with uuid identifier if nothing was provided by data source.

Are you using `vl-interaction-draw` for drawing feature? You can listen for `drawend` on it, as argument you get `ol/Feature` instance and set its id like `feature.setId(id)`.

Later I check automatic identifier setup, but for now looks like you should make this yourself as workaround.

**Comment by chenpion** [comment] 2019-04-22 07:36
@ghettovoice No, in my case I had to use `vl-source-vector` to draw my features.

```html
<vl-layer-vector id="draggable-point-vector"
                 ref="draggablePointVector"
                 :key="`draggable-point-vector-${manuallyUpdateCounter}`"
>
  <vl-style-func :factory="markerIconParams"
                 :key="`style-type-${Date.now()}`"
  />
   <vl-source-vector :features.sync="pointVector"
                    :key="value.coordinates.length"
                    ident="draggable-point"
  ></vl-source-vector>
</vl-layer-vector>
```

### pointVector
```js
// pointVector
[
  {
    geometry: {
      coordinates: [
        [
          [
            -38.82064094313818,
            142.00198278769528
          ],
          [
            -39.05023193359375,
            22.121826171875
          ],
          [
            -20.612823486328125,
            2.12945556640625
          ]
        ]
      ],
      type: 'Polygon'
    },
    id: 'polygonEditorPolygon',
    properties: null,
    type: 'Feature'
  }
]
```

### markerIconParams
```js
markerIconParams() {
  return (feature) => {
    return [
      // polygon
      new Style({
        stroke: new Stroke({
          color: this.polygonStyle.strokeColor,
          width: this.polygonStyle.strokeWidth,
        }),
        fill: new Fill({
          color: this.polygonStyle.fillColor,
        }),
      }),
      // vertices
      new Style(this.readonly
        ? null
        : {
          image: '/assets/icon/...',
          geometry: function(feature) {
            // return the coordinates of the first ring of the polygon
            var coordinates = feature.getGeometry().getCoordinates()[0];
            return new MultiPoint(coordinates);
          },
      }),
    ];
  };
},
```

What I want to do is get the feature's data I clicked, so an automatic generated id might not good enough for me.
Is there any way to set `id` in a specific rule according to it's index ?

**Comment by ghettovoice** [comment] 2019-04-22 17:02
With vl-interaction-select when feature selected you should get selected features in the `features` prop. There them will be in the geojson format. Something like here https://jsfiddle.net/ghettovoice/jebLac2y/ should work also for any geometry.

From your snippets I see that you already set id  `polygonEditorPolygon` of the polygon feature. Can you confirm that when you click on it the selected feature doesn't have this id?

**Comment by chenpion** [comment] 2019-04-22 23:14
<img width="614" alt="螢幕快照 2019-04-23 07 02 40" src="https://user-images.githubusercontent.com/33650282/56538713-5b228700-6596-11e9-969d-9b0d15751d1d.png">

@ghettovoice Thanks for your reply.
I do get a feature with id `polygonEditorPolygon` when I clicked on the `Point`. 
In fact, `vl-interaction-select` detects two features, one is the `Polygon` below, and the `Point` on top. 
What I need is to get the point's `id`. But as it shows in the image, `id` is `undefined`.

**Comment by ghettovoice** [comment] 2019-04-23 16:37
As I understand this points you generate from style function. Actually this is not the features
and should be selected (or be selected as the whole polygon).
Looks like a bug, I need some time to try reproduce it.

**Comment by ghettovoice** [comment] 2019-04-23 16:42
May be you have public test repo with this issue?

**Comment by chenpion** [comment] 2019-04-23 16:47
@ghettovoice I see, I'll try another way to achieve it.

Thanks for your replies.

**Closed** 2020-03-30 18:54 UTC
Labels: clarification, pinned
