### ISSUE TITLE
Uncaught (in promise) TypeError: e.map(...).debounceTime is not a function

### ISSUE THREAD

**Issue by ton212** [ghettovoice/vuelayers#17] opened 2017-10-12 16:47 UTC
I just installed vuelayers on Vue 2.4.2

I placed code from the example with a little modification (center and zoomLavel) as below.
```html
<vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true">
    <vl-view :center="[ 100.4833, 13.7500 ]" :zoom="5" :rotation="0" />

    <vl-layer-tile>
        <vl-source-osm />
    </vl-layer-tile>
</vl-map>
```

The map loaded and control is working but there is an exception thrown by Vuelayers.
```
Uncaught (in promise) TypeError: e.map(...).debounceTime is not a function
    at VueComponent.R (index.umd.min.js?9289:11)
    at VueComponent.subscribeAll (index.umd.min.js?9289:11)
    at VueComponent.boundFn [as subscribeAll] (vue.esm.js?efeb:180)
    at VueComponent.mount (index.umd.min.js?9289:11)
    at boundFn (vue.esm.js?efeb:179)
    at <anonymous>
```

Will this affect anything is the future such as Marker and Clustering?

**Comment by ghettovoice** [comment] 2017-10-12 18:01
It's strange. I can't reproduce the issue https://jsfiddle.net/3z78zzd1/3/
This error may affect events on `vl-view`
Can you show your code ?

**Comment by ton212** [comment] 2017-10-13 06:56
Here is my code where I load the map. I load it in a component.

```html
<template>
    <info-box :hasFooter="true">
        <template slot="header">
            <h3><i class="el-icon-fa-map"></i> Map</h3>
        </template>

        <template slot="body">
            <div class="map">
                <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true">
                    <vl-view :center="[ 100.4833, 13.7500 ]" :zoom="5" :rotation="0" />

                    <vl-layer-tile>
                        <vl-source-osm />
                    </vl-layer-tile>
                </vl-map>
            </div>
        </template>

        <template slot="footer">
            Test footer
        </template>
    </info-box>
</template>
```

```js
<script>
  import InfoBox from './Shared/InfoBox'

  export default {
    components: {
      InfoBox
    },
    props: {
      accountList: {
        type: Array,
        default: () => {
          return []
        }
      }
    }
  }
</script>
```

**Comment by ton212** [comment] 2017-10-13 07:11
I tried init a new Vue project using vue-cli and webpack template without test tools installed. Then I install Vuelayers by `npm install -S vuelayers`.

Here is my main.js
```js
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'

import VueLayers from 'vuelayers'
// import VueLayers styles, needs css-loader
import 'vuelayers/lib/style.css'
// register all vl-* components
Vue.use(VueLayers)

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```
This is my App.vue
```html
<template>
  <div id="app">
    <vl-map :load-tiles-while-animating="true" :load-tiles-while-interacting="true">
      <vl-view :center="[ 100.4833, 13.7500 ]" :zoom="5" :rotation="0" />

      <vl-layer-tile>
          <vl-source-osm />
      </vl-layer-tile>
    </vl-map>
  </div>
</template>
```

```js
<script>
export default {
  name: 'app'
}
</script>
```

The issue still persists.
```
Uncaught (in promise) TypeError: e.map(...).debounceTime is not a function
    at VueComponent.R (index.umd.min.js?9289:11)
    at VueComponent.subscribeAll (index.umd.min.js?9289:11)
    at VueComponent.boundFn [as subscribeAll] (vue.esm.js?efeb:187)
    at VueComponent.mount (index.umd.min.js?9289:11)
    at boundFn (vue.esm.js?efeb:186)
    at <anonymous>
```

**Comment by ghettovoice** [comment] 2017-10-13 07:23
Ok, I'll try to install same project soon

**Comment by ghettovoice** [comment] 2017-10-14 10:21
I already draft the new version **0.7.2**. Try to upgrade and check if issue is still exists.  
Thank you for your bug report!

**Comment by ton212** [comment] 2017-10-14 10:37
I upgraded the library, and it all seem working now :)

**Comment by ghettovoice** [comment] 2017-10-14 15:22
Good! So I close this

**Closed by ghettovoice** 2017-10-14 15:22 UTC
